# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20161006_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailitem',
            name='contentitem_ptr',
        ),
        migrations.RemoveField(
            model_name='feedling',
            name='contentitem_ptr',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
        migrations.RemoveField(
            model_name='task',
            name='feedling',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskset',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskset',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contentitem',
        ),
        migrations.DeleteModel(
            name='Emailitem',
        ),
        migrations.DeleteModel(
            name='Feedling',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Taskset',
        ),
    ]
